export const IPC_CHANNELS = {
  APP_SELECT_FOLDER: 'app.selectFolder',
  APP_TOGGLE_FULLSCREEN: 'app.toggleFullscreen',
  APP_GET_WINDOW_STATE: 'app.getWindowState',
  INDEX_START: 'index.start',
  INDEX_CANCEL: 'index.cancel',
  INDEX_STATUS: 'index.status',
  INDEX_PROGRESS: 'index.onProgress',
  GEO_GET_CLUSTERS: 'geo.getClusters',
  GEO_GET_POINTS: 'geo.getPoints',
  GEO_GET_CLUSTER_MEMBERS: 'geo.getClusterMembers',
  MEDIA_GET_THUMBNAIL: 'media.getThumbnail',
  MEDIA_PREFETCH_THUMBNAILS: 'media.prefetchThumbnails',
  MEDIA_COUNT_PREFETCH_TARGETS: 'media.countPrefetchTargets',
  MEDIA_GET_PREFETCH_TARGET_IDS: 'media.getPrefetchTargetIds',
  MEDIA_GET_HOVER_PREVIEW: 'media.getHoverPreview',
  MEDIA_GET_SOURCE: 'media.getSource',
  MEDIA_OPEN_SOURCE: 'media.openSource',
  SETTINGS_GET: 'settings.get',
  SETTINGS_SET: 'settings.set',
  CITIES_ENSURE_CATALOG: 'cities.ensureCatalog',
  CITIES_GET_CONTINENTS: 'cities.getContinents',
  CITIES_GET_COUNTRIES: 'cities.getCountries',
  CITIES_GET_CITIES: 'cities.getCities',
  CITIES_GET_BY_IDS: 'cities.getByIds',
  CITIES_PROGRESS: 'cities.onProgress',
} as const;
